apiVersion: v1
kind: Service
metadata:
  labels:
  name: jsruleengine-v1-service
  namespace: "jsruleengine-qa"
  labels:
spec:
  type: NodePort
  ports:
  - port: 8790
    targetPort: 8790
    name: port8790
    nodePort: 31180

  selector:
    app: jsruleengine
    deployversion: "v1"
